name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      shell: bash

    - name: Cache Buildozer global directory
      uses: actions/cache@v2
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}

    - name: Cache Buildozer local directory
      uses: actions/cache@v2
      with:
        path: .buildozer
        key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-dev libffi-dev libssl-dev libsqlite3-dev zlib1g-dev libncurses5 libncurses5-dev libreadline-dev libbz2-dev
        pip install --upgrade pip
        pip install buildozer

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: android debug
        buildozer_version: stable

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: ${{ steps.buildozer.outputs.filename }}
