name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-8-jdk unzip wget

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O /tmp/cmdline-tools.zip
        unzip /tmp/cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        rm /tmp/cmdline-tools.zip
        wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        mkdir -p $HOME/android-ndk
        unzip android-ndk-r21e-linux-x86_64.zip -d $HOME/android-ndk
        export ANDROID_NDK_HOME=/home/user/android-ndk
    
        # Move the extracted files to the correct location
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
    
        # Set SDK root explicitly
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platforms;android-29" "build-tools;29.0.3" "ndk;21.4.7075529"

    - name: Set up Android SDK environment variables
      run: |
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/29.0.3:$ANDROID_HOME/ndk/21.4.7075529:$PATH" >> $GITHUB_ENV

    - name: Set up Android SDK
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        sdkmanager --update
        sdkmanager "platforms;android-29" "build-tools;29.0.3" "ndk;21.4.7075529"

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install cython  # Install Cython
        pip install buildozer
        export PATH=$PATH:/home/user/.local/bin  # Add this line to update PATH
        buildozer -v android debug  # Your buildozer command
        
    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command:  buildozer -v android debug
        buildozer_version: stable

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: ${{ steps.buildozer.outputs.filename }}
